<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><AssemblyName>HOK BetaStudio</AssemblyName><Title>HOK BetaStudio</Title><Product>HOK BetaStudio</Product><Description>HOK BetaStudio</Description><RuntimeIdentifier>win-x64</RuntimeIdentifier><ApplicationIcon>../../assets/icons/app/hok-studio.ico</ApplicationIcon><Version>1.4</Version><AssemblyVersion>1.4.0.0</AssemblyVersion><InformationalVersion>$(FileVersion)</InformationalVersion></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31"/><ProjectReference Include="../Hok.Contracts/Hok.Contracts.csproj"/><ProjectReference Include="../Hok.Catalog/Hok.Catalog.csproj"/></ItemGroup></Project>
