using AssetStudio;
using System.Text.Json;
using Newtonsoft.Json;
using JsonSerializer=System.Text.Json.JsonSerializer;
Logger.Silent=true;
Stream input=File.OpenRead(args[0]);if(args[0].EndsWith(".b64")){input.Dispose();input=new System.IO.Compression.GZipStream(new MemoryStream(Convert.FromBase64String(File.ReadAllText(args[0]))),System.IO.Compression.CompressionMode.Decompress);}using var schema=JsonDocument.Parse(input);input.Dispose();string source=Path.GetFullPath(args[1]),output=Path.GetFullPath(args[2]);Directory.CreateDirectory(output);
var trees=new Dictionary<int,TypeTree>();foreach(var c in schema.RootElement.GetProperty("Classes").EnumerateArray()){var node=c.GetProperty("ReleaseRootNode");if(node.ValueKind!=JsonValueKind.Object)continue;var tree=new TypeTree{m_Nodes=[]};void Add(JsonElement n){tree.m_Nodes.Add(new(){m_Type=n.GetProperty("TypeName").GetString(),m_Name=n.GetProperty("Name").GetString(),m_Level=n.GetProperty("Level").GetInt32(),m_ByteSize=n.GetProperty("ByteSize").GetInt32(),m_TypeFlags=n.GetProperty("TypeFlags").GetInt32(),m_MetaFlag=n.GetProperty("MetaFlag").GetInt32(),m_Version=n.GetProperty("Version").GetInt32()});foreach(var sub in n.GetProperty("SubNodes").EnumerateArray())Add(sub);}Add(node);trees[c.GetProperty("TypeID").GetInt32()]=tree;}
var selected=args.Length>3?args[3].Split(',').Select(int.Parse).ToHashSet():null;
if(selected!=null)foreach(var key in trees.Keys.Where(k=>!selected.Contains(k)).ToArray())trees.Remove(key);
var manager=new AssetsManager{Game=GameManager.GetGame(GameType.HonorOfKings),DeferHeavyObjects=new FileInfo(source).Length>128L*1024*1024};manager.LoadFilesReadOnly(source);
var result=new List<object>();var examples=new HashSet<int>();foreach(var file in manager.assetsFileList)foreach(var info in file.m_Objects){if(!file.ParseStatuses.TryGetValue(info.m_PathID,out var old)||old.Status=="typed-complete"||!trees.TryGetValue(info.classID,out var tree))continue;using var r=new ObjectReader(file.reader,file,info,manager.Game);string? error=null;long read=0;try{var data=TypeTreeHelper.ReadType(tree,r);read=r.Position-info.byteStart;if(read!=info.byteSize)throw new InvalidDataException($"Read {read}/{info.byteSize}");if(examples.Add(info.classID))File.WriteAllText(Path.Combine(output,info.classID+".json"),JsonConvert.SerializeObject(data,Formatting.Indented));}catch(Exception e){error=e.Message;read=r.Position-info.byteStart;}result.Add(new{classId=info.classID,id=info.m_PathID.ToString(),size=info.byteSize,read,error,version=file.unityVersion,hash=Convert.ToHexString(info.serializedType.m_OldTypeHash)});}
File.WriteAllText(Path.Combine(output,"objects.json"),JsonSerializer.Serialize(result));Console.WriteLine(JsonSerializer.Serialize(result.Select(x=>JsonSerializer.SerializeToElement(x)).GroupBy(x=>x.GetProperty("classId").GetInt32()).Select(g=>new{classId=g.Key,ok=g.Count(x=>x.GetProperty("error").ValueKind==JsonValueKind.Null),failed=g.Count(x=>x.GetProperty("error").ValueKind!=JsonValueKind.Null),errors=g.Where(x=>x.GetProperty("error").ValueKind!=JsonValueKind.Null).Select(x=>x.GetProperty("error").GetString()).Distinct().Take(3)})));manager.Clear();
