import React,{lazy,Suspense,useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {boot,desktop,placeholder,rpc} from './bridge';
import {locales} from './i18n';
import type {Text} from './i18n';
import type {Asset,Boot,Db,Lang,LoadResult,LoadSummary,Page} from './types';
import {assetDiagnosticTitle,hasLoadDiagnostics,parseStatusText} from './diagnostics';
import {CrystalButton} from './CrystalButton';
import './style.css';
import './entrance.css';
import './drop.css';
import './media.css';
import './replacement.css';
import './qts.css';
import {replacementText} from './replacementText';
import {Portrait,ResourceSync,portraitUrl,useResourceUpdate} from './resources';
import type {AppliedCatalog} from './resources';
import {UnknownDbList} from './UnknownDbList';
import {QtsRawView} from './QtsRawView';
const ImageView=lazy(()=>import('./ImagePreview').then(m=>({default:m.ImageView})));
const ModelView=lazy(()=>import('./Preview').then(m=>({default:m.ModelView})));
const FontPreview=lazy(()=>import('./FontPreview').then(m=>({default:m.FontPreview})));
const CurvePreview=lazy(()=>import('./CurvePreview').then(m=>({default:m.CurvePreview})));
const AudioPlayer=lazy(()=>import('./AudioPlayer').then(m=>({default:m.AudioPlayer})));
const BankPreview=lazy(()=>import('./BankPreview').then(m=>({default:m.BankPreview})));
const fmt=(n:number|string)=>Number(n)>=1048576?(Number(n)/1048576).toFixed(1)+' MB':Number(n)>=1024?(Number(n)/1024).toFixed(1)+' KB':n+' B';
function Icon({name,art}:{name:string;art:string}){return <img className="icon" src={art+'icons/ui/'+name+'.svg'} alt=""/>}

function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null),close=useRef(onClose);close.current=onClose;useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();close.current()}} onClick={e=>{if(e.target===ref.current)close.current()}}><header className="modal-head"><h2>{title}</h2><button className="close-button" onClick={onClose} aria-label="Close">×</button></header>{children}</dialog>}
function PortraitGrid({children,className='hero-grid'}:{children:React.ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);const [columns,setColumns]=useState(1);useLayoutEffect(()=>{const element=ref.current!;const update=()=>{const style=getComputedStyle(element);setColumns(style.display==='grid'?style.gridTemplateColumns.split(' ').length:1)};update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect()},[]);return <div ref={ref} className={className}>{React.Children.map(children,(child,index)=>React.isValidElement<{style?:React.CSSProperties}>(child)?React.cloneElement(child,{style:{...child.props.style,'--delay':(index%columns+Math.floor(index/columns))*38+'ms'} as React.CSSProperties}):child)}</div>}
function BetaTag({text}:{text:string}){const id=React.useId();return <span className="beta-tag" tabIndex={0} aria-describedby={id} aria-label={'Beta: '+text}>Beta<span className="beta-tip" id={id} role="tooltip">{text}</span></span>}
function LoadDiagnostics({result,t,onOpen}:{result:LoadSummary;t:Text;onOpen?:()=>void}){
 const issues=hasLoadDiagnostics(result);
 return <section className={'load-diagnostics '+(issues?'has-issues':'')} aria-label={t.parseCoverage} role="status">
  <div className="diagnostic-heading"><strong>{issues?t.loadNeedsReview:t.parseCoverage}</strong>{onOpen&&<button onClick={onOpen}>{t.viewDiagnostics}</button>}</div>
  <div className="diagnostic-counts">
   {result.objectTableRows!=null&&<span>{t.objectTableRows}: {result.objectTableRows}</span>}
   {result.errorCount!=null&&<span>{t.errorCountLabel}: {result.errorCount}</span>}
   {result.warningCount!=null&&<span>{t.warningCountLabel}: {result.warningCount}</span>}
   {result.errorCount==null&&result.warningCount==null&&result.errors.length>0&&<span>{t.diagnosticMessages}: {result.errors.length}</span>}
  </div>
  {result.parseStatuses&&<div className="parse-summary">{Object.entries(result.parseStatuses).filter(([,count])=>count>0).map(([status,count])=><span key={status}>{parseStatusText(status,t)}: {count}</span>)}</div>}
  {result.parseStatuses&&<p>{t.parseCoverageHint}</p>}
  {result.errorsTruncated&&<p className="diagnostic-truncated">{t.diagnosticsTruncated}</p>}
 </section>;
}
function App(){
 const [lang,setLang]=useState<Lang>(()=>(localStorage.getItem('hok-lang') as Lang)||'zh'),t=locales[lang]||locales.zh;
 const rt=replacementText[lang]||replacementText.zh;
 const [replaced,setReplaced]=useState<Record<string,boolean>>({}),[betaAction,setBetaAction]=useState<'replace'|'rebuild'|null>(null),[rebuildResult,setRebuildResult]=useState<{output:string;reportPath:string}|null>(null);
 const dirty=Object.keys(replaced).length;
 const [catalog,setCatalog]=useState<Boot|null>(null),[hasWorkspace,setHasWorkspace]=useState(false),[dbs,setDbs]=useState<Db[]>([]),[hero,setHero]=useState<string|null>(null),[skin,setSkin]=useState<string|null>(null),[dbId,setDbId]=useState('');
 const [menu,setMenu]=useState(false),[screen,setScreen]=useState('heroes'),[query,setQuery]=useState(''),[assetQuery,setAssetQuery]=useState(''),[type,setType]=useState(''),[page,setPage]=useState<Page>({items:[],page:0,total:0}),[types,setTypes]=useState<Record<string,number>>({});
 const [selected,setSelected]=useState<Record<string,Asset>>({}),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const [assetView,setAssetView]=useState<'assets'|'raw'>('assets');
 const observedAssets=useRef(new Map<string,Asset>());
 const [scanDiagnostics,setScanDiagnostics]=useState<string[]>([]),[loadDiagnostics,setLoadDiagnostics]=useState<string[]>([]),[loadSummary,setLoadSummary]=useState<LoadSummary|null>(null),[logText,setLogText]=useState<string|null>(null);
 const diagnostics=[...scanDiagnostics,...loadDiagnostics];
 const [preview,setPreview]=useState<Asset|null>(null),[previewData,setPreviewData]=useState<{url:string;kind:string;warnings?:string[]}|null>(null),[previewText,setPreviewText]=useState(''),[previewError,setPreviewError]=useState('');
 const [neighbors,setNeighbors]=useState<{previous:Asset|null;next:Asset|null;index:number;total:number}|null>(null),[clearing,setClearing]=useState(false);const operation=useRef(0);
 const [exportBusy,setExportBusy]=useState(false),[exporting,setExporting]=useState(false),[format,setFormat]=useState('auto'),[exportResult,setExportResult]=useState<any>(null);
 const [reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
 const [options,setOptions]=useState({animations:true,blendShapes:true,materials:true,allUv:true,scale:1});const epoch=useRef(0),previewEpoch=useRef(0),exportEpoch=useRef(0);
 const [dragState,setDragState]=useState<'idle'|'over'|'accepted'>('idle');const dragDepth=useRef(0),dropTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),importLock=useRef(false);
 const {update,clearUpdate}=useResourceUpdate(catalog!==null);
 const art=catalog?.artOrigin||(desktop?'https://art.hok.local/':'/assets/');
 const icon=(name:string)=><Icon name={name} art={art}/>;
 useEffect(()=>{boot().then(c=>{setCatalog(c);if(c.initialPaths.length)void open('startup')}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{document.documentElement.lang={zh:'zh-CN',en:'en',vi:'vi'}[lang];localStorage.setItem('hok-lang',lang)},[lang]);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 async function run(label:string,action:()=>Promise<void>){const ticket=++operation.current;setBusy(label);setError('');try{await action()}catch(e){if(ticket===operation.current)setError(e instanceof Error?e.message:String(e))}finally{if(ticket===operation.current)setBusy('')}}
 function resetView(){observedAssets.current.clear();epoch.current++;previewEpoch.current++;exportEpoch.current++;setPreview(null);setPreviewData(null);setNeighbors(null);setExporting(false);setExportBusy(false);setExportResult(null);setReplaced({});setBetaAction(null);setRebuildResult(null);setHero(null);setSkin(null);setDbId('');setPage({items:[],page:0,total:0});setSelected({});setTypes({});setScanDiagnostics([]);setLoadDiagnostics([]);setLoadSummary(null);setLogText(null);setScreen('heroes');setQuery('');setAssetQuery('');setType('');document.querySelector('.workspace')?.scrollTo(0,0)}
 function applyWorkspace(result:any){if(!result)return;resetView();setHasWorkspace(true);setDbs(result.files);setScanDiagnostics(result.errors);if(result.files.length&&result.files.every((d:Db)=>!d.heroId))setHero('__unknown__')}
 async function clearWorkspace(){if(clearing||importLock.current)return;setClearing(true);setMenu(false);++operation.current;resetView();setError('');setBusy(t.clearingWorkspace);try{await Promise.all([rpc('clear'),new Promise(resolve=>setTimeout(resolve,480))]);setHasWorkspace(false);setDbs([])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setClearing(false);setBusy('')}}
 async function applyResources(revision:string){
  if(importLock.current||clearing)return;importLock.current=true;setClearing(true);setMenu(false);++operation.current;resetView();setHasWorkspace(false);setDbs([]);setError('');setBusy(t.clearingWorkspace);
  try{const next=await rpc<AppliedCatalog>('catalogApply',{revision});setCatalog(current=>current?{...current,...next}:current);clearUpdate()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{importLock.current=false;setClearing(false);setBusy('')}
 }
 async function open(mode:string){setMenu(false);if(!desktop){setError(t.onlyDesktop);return;}if(importLock.current)return;importLock.current=true;try{await run(t.loading,async()=>applyWorkspace(await rpc('open',{mode})))}finally{importLock.current=false}}
 useEffect(()=>{
  const isFiles=(e:DragEvent)=>Array.from(e.dataTransfer?.types||[]).includes('Files');
  const reset=()=>{dragDepth.current=0;setDragState('idle')};
  const enter=(e:DragEvent)=>{if(!isFiles(e))return;e.preventDefault();if(busy||importLock.current)return;clearTimeout(dropTimer.current);dragDepth.current++;setDragState('over')};
  const over=(e:DragEvent)=>{if(!isFiles(e))return;e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect=busy||importLock.current?'none':'copy'};
  const leave=(e:DragEvent)=>{if(!isFiles(e))return;e.preventDefault();if(--dragDepth.current<=0)reset()};
  const drop=(e:DragEvent)=>{if(!isFiles(e))return;e.preventDefault();dragDepth.current=0;const files=Array.from(e.dataTransfer?.files||[]);if(busy||importLock.current||!files.length){reset();return}if(!desktop){reset();setError(t.onlyDesktop);return}importLock.current=true;setDragState('accepted');dropTimer.current=setTimeout(()=>setDragState('idle'),700);void run(t.loading,async()=>applyWorkspace(await rpc('drop',{},files))).finally(()=>{importLock.current=false})};
  window.addEventListener('dragenter',enter);window.addEventListener('dragover',over);window.addEventListener('dragleave',leave);window.addEventListener('drop',drop);window.addEventListener('dragend',reset);window.addEventListener('blur',reset);
  return()=>{window.removeEventListener('dragenter',enter);window.removeEventListener('dragover',over);window.removeEventListener('dragleave',leave);window.removeEventListener('drop',drop);window.removeEventListener('dragend',reset);window.removeEventListener('blur',reset)};
 },[busy,t]);
 useEffect(()=>()=>clearTimeout(dropTimer.current),[]);
 async function readSkin(id:string,file=''){if(!hasWorkspace){setSkin(id);return;}if(dirty&&!window.confirm(rt.discard))return;observedAssets.current.clear();setReplaced({});setSkin(id);setDbId(file);setSelected({});setPage({items:[],page:0,total:0});setTypes({});setLoadDiagnostics([]);setLoadSummary(null);setLogText(null);setType('');setAssetQuery('');const version=++epoch.current;await run(t.reading,async()=>{const data=await rpc<LoadResult>('load',{skinId:id,...(file?{dbId:file}:{})});if(version!==epoch.current)return;setTypes(data.result.types);setLoadDiagnostics(data.result.errors);setLoadSummary(data.result);const p=await rpc<Page>('list',{page:0,type:'',query:''});if(version===epoch.current)setPage(p);})}
 async function filter(nextPage=0,nextType=type,nextQuery=assetQuery){if(!skin||busy)return;const version=epoch.current;await run(t.loading,async()=>{const p=await rpc<Page>('list',{page:nextPage,type:nextType,query:nextQuery});if(version===epoch.current)setPage({...p,items:p.items.map(a=>observedAssets.current.get(a.id)||a)})})}
 function recordAsset(previous:Asset,asset?:Asset){
  if(!asset||asset.id!==previous.id)return;
  const old=observedAssets.current.get(asset.id)||previous;observedAssets.current.set(asset.id,asset);
  setPage(p=>({...p,items:p.items.map(a=>a.id===asset.id?asset:a)}));setSelected(s=>s[asset.id]?{...s,[asset.id]:asset}:s);setPreview(p=>p?.id===asset.id?asset:p);
  if(old.parseStatus&&asset.parseStatus&&old.parseStatus!==asset.parseStatus)setLoadSummary(s=>{if(!s?.parseStatuses)return s;const counts={...s.parseStatuses};counts[old.parseStatus!]=Math.max(0,(counts[old.parseStatus!]||0)-1);counts[asset.parseStatus!]=(counts[asset.parseStatus!]||0)+1;return{...s,parseStatuses:counts}});
 }
 async function showPreview(a:Asset){const version=++previewEpoch.current;setPreview(observedAssets.current.get(a.id)||a);setPreviewData(null);setPreviewText('');setPreviewError('');setNeighbors(null);if(a.preview==='bank')return;void rpc('neighbors',{assetId:a.id}).then(n=>{if(version===previewEpoch.current)setNeighbors(n)}).catch(()=>{});try{if(a.preview==='data'){const d=await rpc('dump',{assetId:a.id});if(version===previewEpoch.current){setPreviewText(d.text);recordAsset(a,d.asset)}}else {const d=await rpc<{url:string;kind:string;warnings?:string[];asset?:Asset}>('preview',{assetId:a.id});if(version===previewEpoch.current){setPreviewData(d);recordAsset(a,d.asset)}}}catch(e){if(version===previewEpoch.current)setPreviewError(e instanceof Error?(e.message==='ANIMATION_NO_RELATED_MODEL'?t.animationNoModel:e.message==='ANIMATION_NO_SUPPORTED_TRACKS'?t.animationNoTracks:e.message):String(e))}}
 function closePreview(){previewEpoch.current++;setPreview(null);setPreviewData(null);setPreviewText('');setPreviewError('');setNeighbors(null);if(desktop)void rpc('cancel',{lane:'preview'}).catch(()=>{});}
 async function cancel(){epoch.current++;await rpc('cancel',{lane:'parse'});setReplaced({});setSelected({});setPage({items:[],page:0,total:0});setTypes({});setLoadDiagnostics([]);setLoadSummary(null);setBusy('');setError(t.stopped)}
 async function cancelExport(){exportEpoch.current++;await rpc('cancel',{lane:'export'});setExportBusy(false);setError(t.exportStopped)}
 const unknownDbs=dbs.filter(d=>!d.heroId),unknownView=hero==='__unknown__';
 const heroIds=(hasWorkspace?[...new Set(dbs.map(d=>d.heroId).filter(Boolean))]:(catalog?.heroes.map(h=>h.id)||[])).sort(),heroInfo=catalog?.heroes.find(h=>h.id===hero);
 const heroName=(id:string)=>catalog?.heroes.find(h=>h.id===id)?.name||t.unknownHero+' '+id;
 const heroPic=(id:string)=>portraitUrl(catalog?.heroes.find(h=>h.id===id)?.portrait,art,catalog?.revision||'','placeholders/hero-unknown-256.png');
 const defaultSkin=(id:string)=>/^\d{3}00$/.test(id);
 const catalogSkinIds=(id:string)=>[...new Set([id+'00',...(catalog?.skins.filter(s=>s.heroId===id).map(s=>s.skinId)||[])])].sort();
 const skinIds=(hasWorkspace?[...new Set(dbs.filter(d=>d.heroId===hero).map(d=>d.skinId))]:(hero?catalogSkinIds(hero):[])).sort();
 const visibleHeroIds=heroIds.filter(id=>(id+heroName(id)).toLowerCase().includes(query.toLowerCase()));
 const skinInfo=(id:string)=>catalog?.skins.find(s=>s.skinId===id);
 const unknownIds=skinIds.filter(id=>!defaultSkin(id)&&!skinInfo(id));
 const skinName=(id:string)=>id.startsWith('unknown:')?t.unknown:defaultSkin(id)?t.defaultSkin:skinInfo(id)?.name||t.unknownSkin+' '+String(unknownIds.indexOf(id)+1).padStart(2,'0');
 const unknownList=<UnknownDbList files={unknownDbs.filter(d=>unknownView||(d.name+' '+d.path).toLowerCase().includes(query.toLowerCase()))} title={t.unknownFiles} label={t.unknown} selected={skin} busy={!!busy} onSelect={id=>{setHero('__unknown__');setQuery('');void readSkin(id)}}/>;
 const skinPic=(id:string)=>defaultSkin(id)?heroPic(id.slice(0,3)):portraitUrl(skinInfo(id)?.portrait,art,catalog?.revision||'','placeholders/'+placeholder(id)+'-256.png');
 const chosen=Object.values(selected),formats=useMemo(()=>['auto',...chosen.reduce((list,a)=>list.filter(x=>a.formats.includes(x)),chosen[0]?.formats||[])],[selected]);
 async function betaNow(){const action=betaAction;setBetaAction(null);if(!action)return;if(action==='replace'&&chosen.length!==1)return;const version=epoch.current;await run(action==='replace'?rt.replacing:rt.rebuilding,async()=>{const result=await rpc(action,action==='replace'?{assetId:chosen[0].id}:{});if(!result||version!==epoch.current)return;if(action==='replace')setReplaced(Object.fromEntries(result.items.map((item:{assetId:string})=>[item.assetId,true])));else setRebuildResult(result)})}
 async function exportNow(){const version=++exportEpoch.current;const payload={assetIds:chosen.map(a=>a.id),format,options};setExportBusy(true);setExporting(false);setError('');try{const result=await rpc('export',payload);if(result&&version===exportEpoch.current)setExportResult(result)}catch(e){if(version===exportEpoch.current)setError(e instanceof Error?e.message:String(e))}finally{if(version===exportEpoch.current)setExportBusy(false)}}
 async function exportBank(bank:Asset,format:string){const version=++exportEpoch.current;setExportBusy(true);try{const result=await rpc('export',{assetIds:[bank.id],format,options});if(result&&version===exportEpoch.current)setExportResult(result)}catch(e){if(version===exportEpoch.current)throw e}finally{if(version===exportEpoch.current)setExportBusy(false)}}
 return <div className={'desk '+(reduced?'still':'')}><div className="aurora"/><div className="shell"><header className="topbar"><img className="app-icon" src={art+'icons/app/app-icon-hok-64.png'} alt="HOK"/><span className="wordmark">HOK BetaStudio</span><div className="menu-root"><button className={'menu-button '+(menu?'active':'')} onClick={()=>setMenu(!menu)}>{t.file}{icon('chevron-down')}</button>{menu&&<div className="menu-popover"><button disabled={!!busy} onClick={()=>void open('files')}>{icon('file-plus-2')}{t.openFiles}</button><button disabled={!!busy} onClick={()=>void open('folder')}>{icon('folder-open')}{t.openFolder}</button></div>}</div>{hasWorkspace&&<button className={'sweep-button '+(clearing?'sweeping':'')} disabled={clearing} aria-label={t.clearWorkspace} title={t.clearWorkspace} onClick={()=>void clearWorkspace()}><img src={art+'icons/color/broom.svg'} alt=""/><i/><i/><i/></button>}<ResourceSync update={update} lang={lang} onApply={applyResources}/><div className="title-right"><span className="quiet version">1.3</span><select aria-label={t.language} value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="zh">简体中文</option><option value="en">English</option><option value="vi">Tiếng Việt</option></select></div></header>
 <div className="body-layout"><aside className="sidebar"><nav>{[['heroes','layout-grid',t.heroes],['diagnostics','scan-line',t.diagnostics]].map(([id,ic,label])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}>{icon(ic)}{label}</button>)}</nav></aside>
 <main className="workspace">
 {error&&<div role="alert" className="notice error"><span>{error}</span><button aria-label={t.clear} onClick={()=>setError('')}>×</button></div>}
 {scanDiagnostics.length>0&&screen!=='diagnostics'&&<div role="status" className="notice scan-diagnostics"><span>{t.scanDiagnostics}: {scanDiagnostics.length}</span><button onClick={()=>setScreen('diagnostics')}>{t.viewDiagnostics}</button></div>}
 {screen==='diagnostics'?<><div className="page-head"><h1>{t.diagnostics}</h1><button className="button" disabled={!!busy||!desktop} onClick={()=>void run(t.loading,async()=>{const r=await rpc('logs');setLogText(r.text||t.noLogs)})}>{icon('file-text')}{t.log}</button></div><section className="diagnostic-panel">
  {scanDiagnostics.length>0&&<section><h2>{t.scanDiagnostics}</h2>{scanDiagnostics.map((message,index)=><pre key={index}>{message}</pre>)}</section>}
  {(loadSummary||loadDiagnostics.length>0)&&<section><h2>{t.loadDiagnostics}</h2>{loadSummary&&<LoadDiagnostics result={loadSummary} t={t}/>} {loadDiagnostics.map((message,index)=><pre key={index}>{message}</pre>)}</section>}
  {logText!=null&&<section><h2>{t.rawLog}</h2><pre>{logText}</pre></section>}
  {!diagnostics.length&&!loadSummary&&logText==null&&<p className="quiet">{t.noLogs}</p>}
 </section></>:
 hasWorkspace&&!dbs.length?<div className="empty-workspace"><div className="empty-icon">{icon('folder-open')}</div><h1>{t.empty}</h1><p>{t.emptyHint}</p><div className="button-row"><button className="button primary" disabled={!!busy} onClick={()=>void open('folder')}>{icon('folder-open')}{t.openFolder}</button><button className="button" disabled={!!busy} onClick={()=>void open('files')}>{icon('file-plus-2')}{t.openFiles}</button></div></div>:
 !hero?<><div className="page-head"><div className="heading"><h1>{t.heroes}</h1><span className="count">{visibleHeroIds.length}</span></div><label className="search">{icon('search')}<input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/></label></div><PortraitGrid key={catalog?.revision}>{visibleHeroIds.map(id=><button className="hero-card" key={id} onClick={()=>{setHero(id);setSkin(null);setQuery('')}}><Portrait src={heroPic(id)} fallback={art+'placeholders/hero-unknown-256.png'} alt={heroName(id)}/><strong>{heroName(id)}</strong><span className="mono">{id}</span><span className="quiet">{hasWorkspace?dbs.filter(d=>d.heroId===id).length:catalogSkinIds(id).length} {hasWorkspace?t.dbFiles:t.skinCount}</span></button>)}</PortraitGrid>{hasWorkspace&&unknownList}{!visibleHeroIds.length&&!unknownDbs.length&&catalog&&<p className="quiet">{t.noResults}</p>}</>:
 <><div className="page-head"><div className="heading"><button className="icon-button" aria-label={t.back} disabled={!!busy} onClick={()=>{setHero(null);setSkin(null);setSelected({})}}>{icon('arrow-left')}</button>{!unknownView&&<Portrait key={catalog?.revision} className="heading-portrait" src={heroPic(hero)} fallback={art+'placeholders/hero-unknown-256.png'} alt=""/>}<h1>{unknownView?t.unknownFiles:heroInfo?.name||heroName(hero)}</h1>{!unknownView&&<span className="mono">{hero}</span>}</div><span className="quiet">{unknownView?<>{unknownDbs.length} {t.dbFiles}</>:<>{skinIds.length} {t.skinCount}{hasWorkspace&&<> · {dbs.filter(d=>d.heroId===hero).length} {t.dbFiles}</>}</>}</span></div>
 <div className={'skin-layout '+(skin?'with-assets':'')}>{unknownView?unknownList:<PortraitGrid className="skin-grid" key={hero+':'+catalog?.revision}>{skinIds.map(id=><button disabled={!!busy} className={'skin-card '+(skin===id?'selected':'')} key={id} onClick={()=>void readSkin(id)}><Portrait src={skinPic(id)} fallback={art+'placeholders/'+(defaultSkin(id)?'hero-unknown':placeholder(id))+'-256.png'} alt={skinName(id)}/><div><strong>{skinName(id)}</strong><span className="mono">{id}</span><div className="db-names">{dbs.filter(d=>d.skinId===id).map(d=><span key={d.id} title={d.path}>{d.name}</span>)}</div></div></button>)}</PortraitGrid>}
 {skin&&!hasWorkspace&&<section className="asset-panel catalog-selection"><h2>{skinName(skin)}</h2><p className="mono">{skin}</p><p className="quiet">{t.catalogHint}</p><button className="button" onClick={()=>void open('files')}>{icon('file-plus-2')}{t.openFiles}</button></section>}
 {skin&&hasWorkspace&&<section className="asset-panel"><div className="panel-head"><div><h2>{skinName(skin)}</h2><p className="mono">{unknownView?dbs.find(d=>d.skinId===skin)?.stem:skin}</p></div><button className="icon-button" disabled={!!busy} aria-label={t.refresh} onClick={()=>void readSkin(skin,dbId)}>{icon('refresh-cw')}</button><select aria-label={t.source} value={dbId} disabled={!!busy} onChange={e=>void readSkin(skin,e.target.value)}><option value="">{t.all}</option>{dbs.filter(d=>d.skinId===skin).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div>
 {loadSummary&&<LoadDiagnostics result={loadSummary} t={t} onOpen={()=>setScreen('diagnostics')}/>}
 <div className="button-row qts-tabs"><button className={'button '+(assetView==='assets'?'primary':'')} onClick={()=>setAssetView('assets')}>Assets</button><button className={'button '+(assetView==='raw'?'primary':'')} onClick={()=>setAssetView('raw')}>QtsVFS Raw ({loadSummary?.rawEntries??0})</button></div>
 {assetView==='raw'?<QtsRawView key={skin+dbId} lang={lang} generation={epoch.current}/>:<>
 <div className="asset-toolbar"><select aria-label={t.type} value={type} disabled={!!busy} onChange={e=>{setType(e.target.value);void filter(0,e.target.value)}}><option value="">{t.all}</option>{Object.entries(types).map(([k,n])=><option key={k} value={k}>{k} ({n})</option>)}</select><form className="search" onSubmit={e=>{e.preventDefault();void filter()}}>{icon('search')}<input aria-label={t.search} placeholder={t.search} value={assetQuery} onChange={e=>setAssetQuery(e.target.value)}/></form></div>
 <div className="asset-table-wrap"><table><thead><tr><th><input aria-label={t.selectPage} type="checkbox" checked={page.items.length>0&&page.items.every(a=>selected[a.id])} onChange={e=>setSelected(current=>{const next={...current};page.items.forEach(a=>{if(e.target.checked)next[a.id]=a;else delete next[a.id]});return next})}/></th><th>{t.name}</th><th>{t.type}</th><th>{t.size}</th><th>{t.id}</th></tr></thead><tbody>{page.items.map(a=><tr key={a.id} className={(selected[a.id]?'checked ':'')+(replaced[a.id]?'is-replaced':'')} onDoubleClick={()=>void showPreview(a)}><td><input aria-label={a.name} type="checkbox" checked={!!selected[a.id]} onChange={()=>setSelected(current=>{const next={...current};if(next[a.id])delete next[a.id];else next[a.id]=a;return next})}/></td><td><button className="asset-name" disabled={!!busy} onClick={()=>void showPreview(a)} title={assetDiagnosticTitle(a,t)}>{icon(a.preview==='image'?'image':a.preview==='model'?'box':a.preview==='audio'?'audio-lines':a.preview==='bank'?'folder-open':'braces')}<span>{a.name}</span>{replaced[a.id]&&<span className="replacement-mark" title={rt.staged}>{rt.replaced}</span>}</button></td><td title={assetDiagnosticTitle(a,t)}>{a.type}{a.parseStatus&&<span className={'parse-status '+(a.parseStatus==='parser-failed'?'parse-failed':'')}>{parseStatusText(a.parseStatus,t)}</span>}</td><td className="mono">{fmt(a.bytes)}</td><td className="mono">{a.pathId}</td></tr>)}</tbody></table>{!page.items.length&&!busy&&<div className="empty-assets"><p>{t.noAssets}</p>{diagnostics.length>0&&<button onClick={()=>setScreen('diagnostics')}>{t.parseErrors} ({diagnostics.length})</button>}</div>}</div>
 <div className="pagination"><span>{page.total} {t.counts}</span><button disabled={!!busy||page.page===0} onClick={()=>void filter(page.page-1)}>{t.previous}</button><span>{page.page+1} / {Math.max(1,Math.ceil(page.total/200))}</span><button disabled={!!busy||(page.page+1)*200>=page.total} onClick={()=>void filter(page.page+1)}>{t.next}</button></div>
 <div className="panel-bottom"><span>{t.selected} {chosen.length}</span>{chosen.length===1&&<span className="beta-action"><button className="button replace-button" disabled={!!busy} onClick={()=>setBetaAction('replace')}>{rt.replace}</button><BetaTag text={rt.warning}/></span>}{dirty>0&&<span className="beta-action"><button className="button rebuild-button" disabled={!!busy} onClick={()=>setBetaAction('rebuild')}>{rt.rebuild} ({dirty})</button><BetaTag text={rt.warning}/></span>}<button className="button" disabled={!!busy||!page.total} onClick={()=>void run(t.export,async()=>{await rpc('exportList')})}>{t.list}</button><button className="button primary" disabled={!!busy||exportBusy||!chosen.length} onClick={()=>{setFormat('auto');setExporting(true)}}>{icon('download')}{t.exportSelected}</button></div></>}</section>}</div></>}
 </main></div><footer className="statusbar"><span>{busy||(hasWorkspace?t.base:t.catalog)}</span><span>{dbs.length>0?dbs.length+' '+t.dbFiles:''}</span>{busy&&<><span className="spinner"/><button onClick={()=>void cancel()}>{t.cancel}</button></>}{exportBusy&&<><span className="spinner"/><span>{t.exportBackground}</span><button onClick={()=>void cancelExport()}>{t.cancelExport}</button></>}</footer></div>
 {preview&&<Modal title={preview.name} onClose={closePreview}><div className="preview-content"><Suspense fallback={<div className="stage-state">{t.loading}</div>}>{preview.preview==='bank'?<BankPreview key={preview.id} bank={preview} art={art} t={t} exportBusy={exportBusy} onExport={exportBank}/>:previewError?<div className="preview-failure">{previewError}</div>:previewData?.kind==='font'?<FontPreview key={preview.id} url={previewData.url} t={t}/>:previewData?.kind==='curves'?<CurvePreview key={preview.id} url={previewData.url} t={t}/>:previewData&&['obj','fbx'].includes(previewData.kind)?<ModelView key={preview.id} url={previewData.url} t={t} reduced={reduced} animated={previewData.kind==='fbx'} warnings={previewData.warnings||[]}/>:previewData&&['png','jpg','bmp'].includes(previewData.kind)?<ImageView key={preview.id} url={previewData.url} t={t}/>:previewData?.kind==='wav'?<AudioPlayer key={preview.id} url={previewData.url} art={art} t={t}/>:previewText?<pre className="data-preview">{previewText}</pre>:<div className="stage-state">{t.loading}</div>}</Suspense></div>{preview.preview!=='bank'&&<div className="preview-navigation"><CrystalButton direction="left" art={art} label={t.previousAsset} disabled={!neighbors?.previous} onClick={()=>{if(neighbors?.previous)void showPreview(neighbors.previous)}}/><span className="mono">{neighbors?`${neighbors.index} / ${neighbors.total}`:t.loading}</span><CrystalButton direction="right" art={art} label={t.nextAsset} disabled={!neighbors?.next} onClick={()=>{if(neighbors?.next)void showPreview(neighbors.next)}}/></div>}<div className="preview-meta"><span>{preview.type} · {fmt(preview.bytes)} · {preview.pathId}</span><span title={preview.source}>{preview.source}</span></div></Modal>}
 {exporting&&<Modal title={t.export} onClose={()=>{if(!busy)setExporting(false)}}><div className="export-form"><p>{chosen.length} {t.counts}</p><label>{t.format}<select value={format} onChange={e=>setFormat(e.target.value)}>{formats.map(f=><option key={f} value={f}>{f==='auto'?t.auto:f==='original'?t.original:f==='zip-wem'?t.zipWem:f==='zip-mp3'?t.zipMp3:f.toUpperCase()}</option>)}</select></label>{chosen.some(a=>a.formats.includes('fbx'))&&<fieldset><legend>{t.options}</legend><p className="quiet">{t.modelFormatHint}</p>{(['animations','blendShapes','materials','allUv'] as const).map((key,i)=><label className="checkbox-line" key={key}><input type="checkbox" checked={options[key]} onChange={e=>setOptions(o=>({...o,[key]:e.target.checked}))}/>{[t.animations,t.blend,t.materials,t.uv][i]}</label>)}<label>{t.scale}<input type="number" min=".001" max="1000" step=".1" value={options.scale} onChange={e=>setOptions(o=>({...o,scale:Number(e.target.value)}))}/></label></fieldset>}<p className="quiet">{format==='raw'?t.rawHint:t.exportHint}</p>{chosen.some(a=>a.type==='WwiseAudio'||a.type==='WwiseBank')&&<p className="quiet">{t.audioFormatHint}</p>}</div><div className="modal-actions"><button className="button" disabled={!!busy} onClick={()=>setExporting(false)}>{t.cancel}</button><button className="button primary" disabled={!!busy} onClick={()=>void exportNow()}>{busy||t.start}</button></div></Modal>}
 {betaAction&&<Modal title={(betaAction==='replace'?rt.replace:rt.rebuild)+' · Beta'} onClose={()=>setBetaAction(null)}><div className="export-form"><p className="beta-warning">{rt.warning}</p><p>{rt.raw}</p><p className="quiet">{rt.staged}</p></div><div className="modal-actions"><button className="button" onClick={()=>setBetaAction(null)}>{t.cancel}</button><button className="button primary beta-confirm" onClick={()=>void betaNow()}>{betaAction==='replace'?rt.choose:rt.output}</button></div></Modal>}
 {rebuildResult&&<Modal title={rt.done} onClose={()=>setRebuildResult(null)}><div className="beta-results"><p>{rt.complete}</p><p className="beta-warning">{rt.warning}</p><p>{rebuildResult.output}</p><p>{rt.report}: {rebuildResult.reportPath}</p></div></Modal>}
 {exportResult&&<Modal title={exportResult.failed||exportResult.rawFallback?t.partial:t.done} onClose={()=>setExportResult(null)}><div className="export-results"><p>{t.success} {exportResult.success} · {t.failed} {exportResult.failed}</p>{exportResult.rawFallback>0&&<p role="status">{t.rawFallback}: {exportResult.rawFallback}</p>}{exportResult.results.map((r:any,i:number)=><div key={i} className={r.ok&&!r.rawFallback?'result':'result failure'}><strong>{r.id} · {r.format}</strong><p>{r.ok?r.path:r.error}</p>{r.rawFallback&&<p>{t.rawFallback} ({r.requestedFormat} → RAW): {r.warning}</p>}{r.warnings?.map((message:string,j:number)=><p key={j} role="status">{message}</p>)}</div>)}</div></Modal>}
 {dragState!=='idle'&&<div className={'drop-overlay '+dragState} role="status" aria-live="polite"><div className="drop-target"><span className="drop-symbol">{icon('folder-open')}</span><strong>{dragState==='over'?t.dropTitle:t.dropAccepted}</strong><span>{t.dropHint}</span></div></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
