import React,{useEffect,useRef,useState} from 'react';
import {rpc} from './bridge';
import type {Lang} from './types';
type Entry={id:string;source:string;fileId:string;chunkCount:number;compressedSize:number;uncompressedSize:number;declaredUncompressedSize:number;recoveredSize:number;magic:string;detectedType:string;parseStatus:string;error:string|null;payloadHash:string|null;complete:boolean;objectCount:number};
const text={zh:{search:'搜索 FileId、来源或类型',source:'来源 DB',chunks:'分块',compressed:'压缩字节',expected:'应恢复字节',recovered:'已恢复字节',type:'识别类型',status:'解析状态',export:'导出所选原始数据',previous:'上一页',next:'下一页',copyId:'复制 FileId',copyHash:'复制 SHA256',close:'关闭',loading:'读取中…',hint:'Raw 视图用于追踪完整性，不代表资产已完成语义解析。失败条目导出压缩分块 ZIP，不冒充完整 payload。',copied:'已复制'},en:{search:'Search FileId, source or type',source:'Source DB',chunks:'Chunks',compressed:'Compressed bytes',expected:'Expected bytes',recovered:'Recovered bytes',type:'Detected type',status:'Parse status',export:'Export selected raw data',previous:'Previous',next:'Next',copyId:'Copy FileId',copyHash:'Copy SHA256',close:'Close',loading:'Loading…',hint:'Raw exposure tracks completeness, not semantic support. Failed entries export original chunk ZIPs, never a falsely complete payload.',copied:'Copied'},vi:{search:'Tìm FileId, nguồn hoặc loại',source:'DB nguồn',chunks:'Khối',compressed:'Byte nén',expected:'Byte dự kiến',recovered:'Byte khôi phục',type:'Loại nhận diện',status:'Trạng thái',export:'Xuất dữ liệu gốc đã chọn',previous:'Trước',next:'Sau',copyId:'Sao chép FileId',copyHash:'Sao chép SHA256',close:'Đóng',loading:'Đang đọc…',hint:'Dữ liệu thô phản ánh tính toàn vẹn, không đồng nghĩa đã phân tích đầy đủ. Mục lỗi được xuất thành ZIP chứa các khối gốc.',copied:'Đã sao chép'}};
export function QtsRawView({lang,generation}:{lang:Lang;generation:number}){
 const t=text[lang],dialog=useRef<HTMLDialogElement>(null),ticket=useRef(0),[query,setQuery]=useState(''),[page,setPage]=useState(0),[data,setData]=useState<{total:number;items:Entry[]}>({total:0,items:[]}),[selected,setSelected]=useState<Record<string,boolean>>({}),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const current=++ticket.current;setBusy(true);rpc('rawList',{page,query}).then(r=>{if(ticket.current===current)setData(r)}).catch(e=>{if(ticket.current===current)setError(e.message)}).finally(()=>{if(ticket.current===current)setBusy(false)});return()=>{ticket.current++}},[page,query,generation]);
 useEffect(()=>{if(detail)dialog.current?.showModal();else dialog.current?.close()},[detail]);
 async function inspect(e:Entry){setError('');try{setDetail(await rpc('rawDetail',{id:e.id}))}catch(e){setError(String(e))}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage(t.copied)}catch(e){setError(String(e))}}
 async function exp(){setBusy(true);setError('');try{const r=await rpc('rawExport',{ids:Object.keys(selected)});if(r)setMessage(JSON.stringify(r,null,2))}catch(e){setError(String(e))}finally{setBusy(false)}}
 const hex=detail?.hex?.match(/.{1,32}/g)?.map((line:string,i:number)=>(i*16).toString(16).padStart(8,'0')+'  '+line.match(/../g)?.join(' ')).join('\n');
 return <div className="qts-view"><p className="quiet">{t.hint}</p><input className="qts-search" aria-label={t.search} placeholder={t.search} value={query} onChange={e=>{setPage(0);setQuery(e.target.value)}}/>{error&&<p role="alert">{error}</p>}
 <div className="asset-table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select page" checked={data.items.length>0&&data.items.every(e=>selected[e.id])} onChange={e=>setSelected(old=>{const next={...old};for(const row of data.items){if(e.target.checked)next[row.id]=true;else delete next[row.id]}return next})}/></th>{[t.source,'FileId',t.chunks,t.compressed,t.expected,t.recovered,'Magic',t.type,t.status].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{data.items.map(e=><tr key={e.id} onDoubleClick={()=>void inspect(e)}><td><input type="checkbox" aria-label={e.fileId} checked={!!selected[e.id]} onChange={()=>setSelected(old=>{const next={...old};if(next[e.id])delete next[e.id];else next[e.id]=true;return next})}/></td><td title={e.source}>{e.source.split(/[\\/]/).pop()}</td><td><button className="asset-name mono" onClick={()=>void inspect(e)}>{e.fileId}</button></td><td>{e.chunkCount}</td><td>{e.compressedSize}</td><td title={'Physical field sum: '+e.declaredUncompressedSize}>{e.uncompressedSize}</td><td>{e.recoveredSize}</td><td className="mono">{e.magic.slice(0,16)}</td><td>{e.detectedType}</td><td title={e.error||''}>{e.parseStatus}</td></tr>)}</tbody></table></div>
 <div className="pagination"><span>{busy?t.loading:data.total}</span><button disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>{t.previous}</button><span>{page+1} / {Math.max(1,Math.ceil(data.total/200))}</span><button disabled={busy||(page+1)*200>=data.total} onClick={()=>setPage(p=>p+1)}>{t.next}</button></div><button className="button" disabled={busy||!Object.keys(selected).length} onClick={()=>void exp()}>{t.export} ({Object.keys(selected).length})</button>{message&&<pre className="data-preview">{message}</pre>}
 <dialog ref={dialog} onCancel={()=>setDetail(null)}><header className="modal-head"><h2>{detail?.entry.fileId}</h2><button onClick={()=>setDetail(null)}>{t.close}</button></header>{detail&&<div className="qts-detail"><div className="button-row"><button className="button" onClick={()=>void copy(detail.entry.fileId)}>{t.copyId}</button><button className="button" disabled={!detail.entry.payloadHash} onClick={()=>void copy(detail.entry.payloadHash)}>{t.copyHash}</button></div><pre>{JSON.stringify(detail.entry,null,2)}</pre><p>{detail.explanation}</p><pre>{JSON.stringify(detail.chunks,null,2)}</pre>{detail.metadata?.length>0&&<pre>{JSON.stringify(detail.metadata,null,2)}</pre>}<h3>Hex {detail.hexTruncated?'(0–4095)':''}</h3><pre>{hex}</pre></div>}</dialog></div>;
}
