<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>Hok.Worker</AssemblyName><RuntimeIdentifier>win-x64</RuntimeIdentifier></PropertyGroup><ItemGroup><ProjectReference Include="../Hok.Legacy/Hok.Legacy.csproj"/><ProjectReference Include="../Hok.Contracts/Hok.Contracts.csproj"/><ProjectReference Include="../Hok.Rebuild/Hok.Rebuild.csproj"/></ItemGroup></Project>
