using AssetStudio;
using System.Security.Cryptography;
using System.Text.Json;
using System.IO.Compression;
namespace Hok.Worker;
internal static partial class Program
{
 static readonly Dictionary<string,QtsEntryRecord> RawIndex=[];
 static readonly List<KeyValuePair<string,QtsEntryRecord>> RawRows=[];
 static void LinkResourceTypes(){
  if(manager is null)return;
  foreach(var obj in Objects.Values)if(GetStream(obj) is{} stream)IdentifyStream(obj,stream.Path,stream.Kind);
 }
 static object RawRow(string id,QtsEntryRecord e,bool detail=false)=>new{id,source=e.Source,fileId=e.FileId.ToString(),chunkCount=e.Chunks.Length,compressedSize=e.CompressedBytes,declaredUncompressedSize=e.Chunks.Sum(c=>(long)c.Chunk.UncompressedSize),uncompressedSize=e.ExpectedBytes,recoveredSize=e.PayloadBytes,complete=e.Complete,magic=Convert.ToHexString(e.Head(16)),detectedType=e.AssetTypes??e.Kind,parseStatus=e.ParseStatus,error=e.Error,payloadHash=detail?e.Hash:null,objectCount=e.ObjectCount};
 static QtsEntryRecord Raw(string id)=>RawIndex.TryGetValue(id,out var e)?e:throw new InvalidOperationException("Raw entry no longer loaded");
 static object RawList(JsonElement p){string query=p.TryGetProperty("query",out var q)?q.GetString()??"":"";int page=p.TryGetProperty("page",out var n)?Math.Max(0,n.GetInt32()):0;var filtered=query.Length==0?RawRows:RawRows.Where(x=>x.Key.Contains(query,StringComparison.OrdinalIgnoreCase)||x.Value.Source.Contains(query,StringComparison.OrdinalIgnoreCase)||(x.Value.AssetTypes??x.Value.Kind).Contains(query,StringComparison.OrdinalIgnoreCase)).ToList();return new{total=filtered.Count,page,items=filtered.Skip(checked(page*200)).Take(200).Select(x=>RawRow(x.Key,x.Value)).ToArray()};}
 static object ChunkRow(QtsChunkState c)=>new{entryOffset=c.Chunk.Offset-32,offset=c.Chunk.Offset,mainBlock=c.Chunk.MainBlock,subBlock=c.Chunk.SubBlock,compressedSize=c.Chunk.CompressedSize,declaredUncompressedSize=c.Chunk.UncompressedSize,expectedBytes=c.ExpectedBytes,recoveredBytes=c.RecoveredBytes,codec=c.Codec,error=c.Error};
 static object[] EntryMetadata(QtsEntryRecord e)=>manager!.assetsFileList.Where(f=>f.originalPath==e.Source&&f.containerEntryId==e.FileId.ToString()).Select(f=>(object)new{
  source=f.fullName,f.unityVersion,containerOffset=f.containerByteOffset,objectCount=f.m_Objects.Count,
  types=f.m_Types.Select(t=>new{classId=t.classID,scriptIndex=t.m_ScriptTypeIndex,dependencies=t.m_TypeDependencies,typeHash=t.m_OldTypeHash==null?null:Convert.ToHexString(t.m_OldTypeHash)}),
  managedReferenceTypes=f.m_RefTypes?.Select(t=>new{index=t.m_ScriptTypeIndex,className=t.m_KlassName,nameSpace=t.m_NameSpace,assembly=t.m_AsmName,typeHash=t.m_OldTypeHash==null?null:Convert.ToHexString(t.m_OldTypeHash)}),
  externalFiles=f.m_Externals.Select(t=>new{t.guid,t.type,path=t.pathName})}).ToArray();
 static object RawDetail(JsonElement p){var id=p.GetProperty("id").GetString()!;var e=Raw(id);return new{entry=RawRow(id,e,true),hex=Convert.ToHexString(e.Head(4096)),hexTruncated=e.PayloadBytes>4096,chunks=e.Chunks.Select(ChunkRow).ToArray(),metadata=EntryMetadata(e),explanation="declaredUncompressedSize preserves the physical field. For validated stored index/package records this is a marker, not a decoded byte count; uncompressedSize uses the complete stored record length."};}
 static object RawExport(JsonElement p){var output=Path.GetFullPath(p.GetProperty("output").GetString()!);Directory.CreateDirectory(output);var results=new List<object>();int success=0;foreach(var value in p.GetProperty("ids").EnumerateArray()){string id=value.GetString()!;try{var e=Raw(id);string stem=Path.GetFileNameWithoutExtension(e.Source)+"_"+e.FileId+"_"+Guid.NewGuid().ToString("N")[..6];string target=Path.Combine(output,stem+(e.Complete?".bin":".chunks.zip"));
    if(e.Complete)e.Export(target);else{using var zip=ZipFile.Open(target,ZipArchiveMode.Create);for(int i=0;i<e.Chunks.Length;i++){var c=e.Chunks[i];using var input=File.OpenRead(e.Source);input.Position=c.Chunk.Offset;using var member=zip.CreateEntry($"{i:D4}-{c.Chunk.MainBlock}-{c.Chunk.SubBlock}.compressed",CompressionLevel.NoCompression).Open();var left=c.Chunk.CompressedSize;var buffer=new byte[65536];while(left>0){int n=input.Read(buffer,0,Math.Min(left,buffer.Length));if(n==0)throw new EndOfStreamException();member.Write(buffer,0,n);left-=n;}}}
    File.WriteAllText(target+".json",JsonSerializer.Serialize(new{entry=RawRow(id,e,true),chunks=e.Chunks.Select(ChunkRow),metadata=EntryMetadata(e)},Json));success++;results.Add(new{id,ok=true,path=target});
   }catch(Exception ex){results.Add(new{id,ok=false,error=ex.Message});}}
   return new{success,failed=results.Count-success,results};
 }
 static object RawAudit(JsonElement p){
  if(manager is null)throw new InvalidOperationException("Nothing loaded");string output=Path.GetFullPath(p.GetProperty("output").GetString()!);Directory.CreateDirectory(output);string failed=p.TryGetProperty("failedChunks",out var f)?Path.GetFullPath(f.GetString()!):Path.Combine(output,"failed_chunks");Directory.CreateDirectory(failed);var summaries=new List<object>();
  foreach(var db in manager.QtsDatabases){string key=Path.GetFileNameWithoutExtension(db.Source)+"_"+Hash(db.Source);using var rows=new StreamWriter(Path.Combine(output,key+".entries.jsonl"));var groups=new Dictionary<string,(int Count,long Bytes,double EntropySum)>();long recovered=0,expected=0,compressed=0,declared=0,unknownBytes=0;int chunks=0,okChunks=0,ok=0,unknown=0,parsed=0;
   foreach(var e in db.Entries){expected+=e.ExpectedBytes;compressed+=e.CompressedBytes;chunks+=e.Chunks.Length;okChunks+=e.Chunks.Count(c=>c.Error is null);declared+=e.Chunks.Sum(c=>(long)c.Chunk.UncompressedSize);if(e.Complete){ok++;recovered+=e.PayloadBytes;}if(e.ObjectCount>0)parsed++;bool unclassified=e.Complete&&e.ParseStatus is "unclassified-stream" or "parser-failed";
    double? entropy=null;if(unclassified){unknown++;unknownBytes+=e.PayloadBytes;var histogram=new long[256];using var stream=e.Open();var buffer=new byte[65536];int n;while((n=stream.Read(buffer))>0)for(int i=0;i<n;i++)histogram[buffer[i]]++;double ent=0;foreach(var count in histogram)if(count>0){double probability=(double)count/e.PayloadBytes;ent-=probability*Math.Log2(probability);}entropy=ent;string group=Convert.ToHexString(e.Head(4))+"/"+(e.PayloadBytes%16==0?"aligned16":"unaligned");var old=groups.GetValueOrDefault(group);groups[group]=(old.Count+1,old.Bytes+e.PayloadBytes,old.EntropySum+ent);}
    foreach(var c in e.Chunks.Where(c=>c.Error is not null)){using var source=File.OpenRead(e.Source);source.Position=c.Chunk.Offset;byte[] bytes=new byte[c.Chunk.CompressedSize];source.ReadExactly(bytes);var dest=Path.Combine(failed,key+"_"+e.FileId+"_"+c.Chunk.Offset+".bin");File.WriteAllBytes(dest,bytes);File.WriteAllText(dest+".json",JsonSerializer.Serialize(new{source=e.Source,fileId=e.FileId.ToString(),chunk=ChunkRow(c),first64=Convert.ToHexString(bytes.AsSpan(0,Math.Min(64,bytes.Length)))},Json));}
    rows.WriteLine(JsonSerializer.Serialize(new{fileId=e.FileId.ToString(),e.Complete,expectedBytes=e.ExpectedBytes,recoveredBytes=e.PayloadBytes,e.Kind,e.ParseStatus,e.AssetTypes,e.ObjectCount,sha256=e.Hash,first16=Convert.ToHexString(e.Head(16)),first64=Convert.ToHexString(e.Head()),entropy,error=e.Error,chunks=e.Chunks.Select(ChunkRow)},Json));
   }
   int rawVisible=RawRows.Count(r=>r.Value.Source==db.Source&&r.Value.Complete);
   using var original=File.OpenRead(db.Source);var summary=new{source=db.Source,physicalDbBytes=db.Size,sha256=Convert.ToHexString(SHA256.HashData(original)),header=db.Index.Header,tableCount=db.Index.Tables.Count,blockCount=db.Index.Blocks.Count,entryCount=db.Entries.Count,chunkCount=chunks,declaredCompressedBytes=compressed,physicalUncompressedFieldSum=declared,declaredUncompressedBytes=expected,recoveredPayloadBytes=recovered,rawUnknownBytes=unknownBytes,failedBytes=expected-recovered,entryCoverage=db.Entries.Count==0?1:(double)ok/db.Entries.Count,chunkCoverage=chunks==0?1:(double)okChunks/chunks,byteCoverage=expected==0?1:(double)recovered/expected,rawExposureCoverage=ok==0?1:(double)rawVisible/ok,rawListingRecoveredEntries=rawVisible,rawExposureEvidence="Worker rawList index; frontend page enumeration verified separately",parsedEntries=parsed,rawEntries=ok-parsed,rawUnknown=unknown,failed=db.Entries.Count-ok,parsedAssets=db.Entries.Sum(e=>e.ObjectCount),exceptions=db.Index.Issues};
   File.WriteAllText(Path.Combine(output,key+".json"),JsonSerializer.Serialize(summary,new JsonSerializerOptions(Json){WriteIndented=true,IncludeFields=true}));File.WriteAllText(Path.Combine(output,key+".unknown-groups.json"),JsonSerializer.Serialize(groups.OrderByDescending(g=>g.Value.Count).Select(g=>new{signature=g.Key,files=g.Value.Count,bytes=g.Value.Bytes,meanEntropy=g.Value.EntropySum/g.Value.Count}),Json));summaries.Add(summary);
  }return summaries;
 }
}
